import images from './images';

const kebab = [
    {
        title: 'Chicken tikka kebab',
        price: '$13.99',
    },
    {
        title: 'Murgh Malai Kebab',
        price: '$13.99',
    },
    {
        title: 'Tandoori chicken',
        price: '$14.99',
    },
    {
        title: 'Achari Kebab',
        price: '$13.99',
    },
    {
        title: 'Hariyai Chicken tikka Kebab',
        price: '$13.99',
    },
    {
        title: 'Hyderabad Gongura Kebab',
        price: '$13.99',
    },
];

const wraps = [
    {
        title: 'Butter Chicken Malai Tikka',
        price: '$13.99',
    },
    {
        title: "Chicken Tikka Masaa Wrap",
        price: '$13.99',
    },
    {
        title: 'Chennai Street Masala Wrap',
        price: '$13.99',
    },
    {
        title: 'Lamb Bugari Wrap',
        price: '$14.99',
    },
    {
        title: 'Chicken Chettinadu Wrap',
        price: '$13.99',
    },
];

const awards = [
    {
        imgUrl: images.award02,
        title: 'Fully Hygenic',
        subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
    },
    {
        imgUrl: images.award01,
        title: 'Rising Star',
        subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
    },
    {
        imgUrl: images.award05,
        title: 'AA Hospitality',
        subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
    },
    {
        imgUrl: images.award03,
        title: 'Outstanding Chef',
        subtitle: 'Lorem ipsum dolor sit amet, consectetur.',
    },
];

export const menu = [

    {
        id: 1,
        category: 'tandoori non veg',
        title: 'Tandoori Chicken',
        price: '$14.99',
        tags: 'Bone in',
        description: 'Succulent chicken marinated in yogurt and aromatic spices, cooked to perfection in a traditional clay oven, bursting with flavor and color.',
        todaySpecial: false
    },
    {
        id: 2,
        category: 'tandoori non veg',
        title: 'Chicken Tikka Kebab',
        price: '$13.99',
        tags: '',
        description: 'Tender chunks of chicken marinated in a spicy yogurt mixture, skewered and grilled to perfection, bursting with flavor',
        todaySpecial: false
    },
    {
        id: 3,
        category: 'tandoori non veg',
        title: 'Murgh Malai Kebab',
        price: '$13.99',
        tags: '',
        description: 'Creamy and succulent chicken kebabs marinated in a rich blend of cream, cheese, and spices, grilled to perfection for a melt-in-your-mouth experience.',
        todaySpecial: false
    },
    {
        id: 4,
        category: 'tandoori non veg',
        title: 'House Special Lamb Kebab',
        price: '$13.99',
        tags: '',
        description: 'Exquisite lamb kebabs, expertly seasoned with a blend of house spices, grilled to tender perfection, and bursting with savory flavor',
        todaySpecial: false,
    },
    {
        id: 5,
        category: 'tandoori non veg',
        title: 'Chicken mix platter',
        price: '$17.99',
        tags: '',
        description: 'A delectable assortment of chicken delicacies including tandoori chicken, chicken tikka, and chicken malai kebab, served with mint chutney and tangy tamarind sauce',
        todaySpecial: false,
    },
    {
        id: 6,
        category: 'tandoori non veg',
        title: 'Reshmi kebab',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken kebabs delicately marinated in a creamy mixture of yogurt, cashew nut paste, and aromatic spices, grilled to perfection for a melt-in-your-mouth experience',
        todaySpecial: false,
    },
    {
        id: 7,
        category: 'tandoori non veg',
        title: 'Tandoori malai chicken',
        price: '$15.99',
        tags: 'Bone in',
        description: 'Tender chicken pieces marinated in a luxurious blend of cream, yogurt, and aromatic spices, expertly grilled in a traditional clay oven, resulting in a creamy and flavorful rendition of the classic tandoori chicken.',
        todaySpecial: false,
    },
    {
        id: 8,
        category: 'tandoori non veg',
        title: 'Tandoori Reshmi chicken',
        price: '$15.99',
        tags: 'Bone in',
        description: 'Tender chicken pieces, enveloped in a luscious blend of cream, yogurt, cashew paste, and aromatic spices, grilled to perfection in a traditional clay oven, offering a sumptuously creamy and delicately spiced variation of the classic tandoori chicken',
        todaySpecial: false,
    },
    {
        id: 9,
        category: 'tandoori non veg',
        title: 'Tandoori hariyali chicken',
        price: '$15.99',
        tags: 'Bone in',
        description: 'Juicy chicken pieces marinated in a vibrant green mixture of fresh cilantro, mint, yogurt, and spices, grilled to perfection in a traditional clay oven, delivering a burst of fresh flavors and aromatic herbs',
        todaySpecial: false,
    },
    {
        id: 10,
        category: 'tandoori non veg',
        title: 'Hyderabad gongura kebab',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken pieces, marinated in a zesty gongura (sorrel leaves) paste blended with traditional Hyderabad spices, grilled to perfection, delivering a tangy and aromatic culinary experience.',
        todaySpecial: false,
    },
    {
        id: 13,
        category: 'tandoori non veg',
        title: 'Hariyali chicken tikka kebab',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken pieces coated in a vibrant green marinade crafted from fresh cilantro, mint, yogurt, and spices, grilled to perfection, offering a burst of fresh flavors and aromatic herbs.',
        todaySpecial: false,
    },
    {
        id: 14,
        category: 'tandoori non veg',
        title: 'Achari kebab',
        price: '$13.99',
        tags: '',
        description: 'Chicken pieces marinated in a tangy blend of pickling spices and yogurt, grilled to perfection, offering a delightful balance of tanginess and spice reminiscent of traditional Indian pickles.',
        todaySpecial: false,
    },
    {
        id: 15,
        category: 'tandoori non veg',
        title: 'Tandoori veg Paneer kebab',
        price: '$12.99',
        tags: '',
        description: 'Paneer cubes marinated in a flavorful blend of yogurt, spices, and aromatic herbs, grilled to perfection in a traditional clay oven, offering a delicious vegetarian twist on the classic tandoori kebab.',
        todaySpecial: false,
    },
    {
        id: 16,
        category: 'Wraps Non Veg',
        title: 'Butter chicken malai tikka',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken chunks enveloped in a velvety marinade boasting the richness of butter, cream, and aromatic spices, expertly grilled to create a lusciously creamy and flavorful tikka experience, wrapped in a soft and thin rumali roti for a delightful handheld indulgence.',
        todaySpecial: false,
    },
    {
        id: 17,
        category: 'Wraps Non Veg',
        title: 'Chicken tikka masala wrap',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken tikka pieces smothered in a rich and aromatic masala sauce, wrapped in a soft and thin rumali roti for a flavorful handheld delight, perfect for on-the-go indulgence.',
        todaySpecial: false,
    },
    {
        id: 18,
        category: 'Wraps Non Veg',
        title: 'Chennai Street chicken wrap',
        price: '$13.99',
        tags: '',
        description: 'Spicy chicken cooked with South Indian spices, wrapped in a soft and thin rumali roti, inspired by the vibrant flavors of Chennai street food scene, offering a savory and satisfying handheld treat',
        todaySpecial: false,
    },
    {
        id: 19,
        category: 'Wraps Non Veg',
        title: 'Hariyali chicken green garden wrap',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken pieces coated in a vibrant green marinade crafted from fresh cilantro, mint, yogurt, and spices, wrapped in a soft and thin rumali roti, offering a burst of fresh flavors and aromatic herbs, reminiscent of a verdant garden.',
        todaySpecial: false,
    },
    {
        id: 20,
        category: 'Wraps Non Veg',
        title: 'Lamp Bugari wrap',
        price: '$14.99',
        tags: '',
        description: 'Tender lamb pieces marinated in a flavorful blend of Mediterranean spices, wrapped in a soft and thin rumali roti, offering a savory and aromatic experience inspired by Mediterranean cuisine.',
        todaySpecial: false,
    },
    {
        id: 21,
        category: 'Wraps Non Veg',
        title: 'Chicken chettinadu wrap',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked in the rich and aromatic spices of Chettinad cuisine, wrapped in a soft and thin rumali roti, offering a flavorful and satisfying taste of South Indian culinary tradition.',
        todaySpecial: false,
    },
    {
        id: 22,
        category: 'Curry Non Veg',
        title: 'Butter Chicken',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked in a creamy and flavorful tomato-based sauce, enriched with butter, cream, and aromatic spices, offering a rich and indulgent taste of North Indian cuisine.',
        todaySpecial: false,
    },
    {
        id: 23,
        category: 'Curry Non Veg',
        title: 'Chicken tikka masala',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken tikka pieces simmered in a rich and creamy tomato-based sauce, infused with aromatic spices, offering a flavorful and comforting taste of Indian cuisine.',
        todaySpecial: false,
    },
    {
        id: 24,
        category: 'Curry Non Veg',
        title: 'kadai Chicken',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked with bell peppers, onions, tomatoes, and a blend of aromatic spices, simmered to perfection in a rich and flavorful curry sauce, offering a satisfying taste of North Indian cuisine.',
        todaySpecial: false,
    },
    {
        id: 25,
        category: 'Curry Non Veg',
        title: 'Chennai chicken curry',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked in a spicy and aromatic curry sauce, infused with the vibrant flavors of South Indian cuisine, offering a delicious and authentic taste of Chennai culinary heritage.',
        todaySpecial: false,
    },
    {
        id: 26,
        category: 'Curry Non Veg',
        title: 'Chicken pepper fry',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken pieces marinated in a spicy blend of black pepper, garlic, and other aromatic spices, stir-fried to perfection, offering a flavorful and peppery twist on a classic chicken dish.',
        todaySpecial: false,
    },
    {
        id: 27,
        category: 'Curry Non Veg',
        title: 'Goat pepper fry',
        price: '$13.99',
        tags: '',
        description: 'Tender goat meat marinated in a spicy blend of black pepper, garlic, and other aromatic spices, stir-fried to perfection, offering a flavorful and peppery twist on a classic goat dish.',
        todaySpecial: false,
    },
    {
        id: 28,
        category: 'Curry Non Veg',
        title: 'Gongura chicken curry',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked in a tangy and flavorful curry sauce made with gongura (sorrel) leaves, onions, tomatoes, and a blend of aromatic spices, offering a unique and delicious taste of Andhra cuisine.',
        todaySpecial: false,
    },
    {
        id: 29,
        category: 'Curry Non Veg',
        title: 'Chicken chettinadu',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked in a rich and spicy gravy infused with the bold flavors of Chettinad cuisine, featuring a blend of roasted spices, coconut, and curry leaves, offering an authentic taste of South Indian culinary tradition.',
        todaySpecial: false,
    },
    {
        id: 30,
        category: 'Curry Non Veg',
        title: 'Goat chettinadu',
        price: '$14.99',
        tags: '',
        description: 'Tender goat meat cooked in a rich and spicy gravy infused with the bold flavors of Chettinad cuisine, featuring a blend of roasted spices, coconut, and curry leaves, offering an authentic taste of South Indian culinary tradition.',
        todaySpecial: false,
    },
    {
        id: 31,
        category: 'Curry Non Veg',
        title: 'Chicken mugalai',
        price: '$13.99',
        tags: '',
        description: 'Tender chicken cooked in a rich and creamy gravy, enriched with cashews, almonds, and aromatic spices, offering a luxurious and flavorful taste of Mughlai cuisine.',
        todaySpecial: false,
    },
    {
        id: 32,
        category: 'Curry Non Veg',
        title: 'Gongura goat curry',
        price: '$14.99',
        tags: '',
        description: 'Tender goat meat cooked in a tangy and flavorful curry sauce made with gongura (sorrel) leaves, onions, tomatoes, and a blend of aromatic spices, offering a unique and delicious taste of Andhra cuisine.',
        todaySpecial: false,
    },
    {
        id: 33,
        category: 'Curry Non Veg',
        title: 'Goat mugalai',
        price: '$14.99',
        tags: '',
        description: 'Tender goat meat cooked in a rich and creamy gravy, enriched with cashews, almonds, and aromatic spices, offering a luxurious and flavorful taste of Mughlai cuisine.',
        todaySpecial: false,
    },
    {
        id: 34,
        category: 'Curry Non Veg',
        title: 'Goat curry',
        price: '$14.99',
        tags: '',
        description: 'Tender goat meat cooked in a rich and flavorful curry sauce made with onions, tomatoes, and a blend of aromatic spices, offering a delicious and hearty taste of traditional Indian cuisine.',
        todaySpecial: false,
    },
    {
        id: 35,
        category: 'Thandoori veg',
        title: 'Paneer kebab',
        price: '$12.99',
        tags: '',
        description: 'Soft and succulent paneer cubes marinated in a flavorful blend of yogurt, spices, and aromatic herbs, grilled to perfection, offering a delicious vegetarian alternative to traditional meat kebabs.',
        todaySpecial: false,
    },
    {
        id: 36,
        category: 'Thandoori veg',
        title: 'Mushroom kebab',
        price: '$12.99',
        tags: '',
        description: 'Juicy mushroom caps marinated in a savory blend of spices, herbs, and tangy yogurt, grilled to perfection, offering a flavorful and satisfying vegetarian kebab option.',
        todaySpecial: false,
    },
    {
        id: 37,
        category: 'Thandoori veg',
        title: 'Veg special platter',
        price: '$15.99',
        tags: '',
        description: 'An assortment of flavorful vegetarian delicacies including paneer tikka, vegetable seekh kebab, samosas, and tandoori vegetables, served with mint chutney and tangy tamarind sauce, offering a delightful and satisfying vegetarian feast.',
        todaySpecial: false,
    },
    {
        id: 38,
        category: 'Wraps Veg',
        title: 'Butter paneer wrap',
        price: '$12.99',
        tags: '',
        description: 'Soft paneer cubes simmered in a rich and creamy tomato-based sauce, infused with butter, cream, and aromatic spices, wrapped in a soft and thin rumali roti for a delicious and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 39,
        category: 'Wraps Veg',
        title: 'House special paneer tikka',
        price: '$12.99',
        tags: '',
        description: 'Soft and succulent paneer cubes marinated in a signature blend of spices and yogurt, grilled to perfection, wrapped in a soft and thin rumali roti for a flavorful and satisfying vegetarian handheld meal.',
        todaySpecial: false,
    },
    {
        id: 40,
        category: 'Wraps Veg',
        title: 'Hariyali mushroom green',
        price: '$15.99',
        tags: '',
        description: 'Juicy mushroom caps coated in a vibrant green marinade crafted from fresh cilantro, mint, yogurt, and spices, wrapped in a soft and thin rumali roti, offering a burst of fresh flavors and aromatic herbs in a convenient handheld form.',
        todaySpecial: false,
    },
    {
        id: 41,
        category: 'Wraps Veg',
        title: 'garden wrap',
        price: '$11.99',
        tags: '',
        description: 'A delightful wrap filled with fresh garden vegetables, such as lettuce, tomatoes, cucumbers, and bell peppers, wrapped in a soft and thin rumali roti, offering a refreshing and healthy vegetarian handheld option.',
        todaySpecial: false,
    },
    {
        id: 42,
        category: 'Wraps Veg',
        title: 'Mix veg wrap',
        price: '$15.99',
        tags: '',
        description: 'A flavorful wrap filled with an assortment of mixed vegetables, such as carrots, bell peppers, corn, and peas, seasoned with aromatic spices, wrapped in a soft and thin rumali roti, offering a tasty and satisfying vegetarian handheld option.',
        todaySpecial: false,
    },
    {
        id: 43,
        category: 'Wraps Veg',
        title: 'Paneer butter masala',
        price: '$12.99',
        tags: '',
        description: 'Soft paneer cubes cooked in a rich and creamy tomato-based sauce, infused with butter, cream, and aromatic spices, wrapped in a soft and thin rumali roti for a delicious and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 44,
        category: 'Wraps Veg',
        title: 'Paneer tikka masala',
        price: '$12.99',
        tags: '',
        description: 'Soft paneer cubes marinated in a flavorful blend of spices and yogurt, cooked in a rich and creamy tomato-based sauce, infused with aromatic spices, wrapped in a soft and thin rumali roti for a delicious and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 45,
        category: 'Wraps Veg',
        title: 'Veg makhani',
        price: '$12.99',
        tags: '',
        description: 'Assorted vegetables cooked in a rich and creamy tomato-based sauce, infused with butter, cream, and aromatic spices, wrapped in a soft and thin rumali roti for a flavorful and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 46,
        category: 'Wraps Veg',
        title: 'Mushroom masala',
        price: '$12.99',
        tags: '',
        description: 'Juicy mushroom caps cooked in a rich and flavorful tomato-based sauce, infused with aromatic spices, wrapped in a soft and thin rumali roti for a delicious and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 47,
        category: 'Wraps Veg',
        title: 'Kadai paneer',
        price: '$12.99',
        tags: '',
        description: 'Soft paneer cubes cooked with bell peppers, onions, tomatoes, and a blend of aromatic spices, offering a flavorful and satisfying vegetarian dish inspired by North Indian cuisine.',
        todaySpecial: false,
    },
    {
        id: 48,
        category: 'Wraps Veg',
        title: 'Malai Kofta',
        price: '$12.99',
        tags: '',
        description: 'Delicious dumplings made from paneer, potatoes, and mixed vegetables, served in a rich and creamy tomato-based sauce infused with cashews, cream, and aromatic spices, wrapped in a soft and thin rumali roti for a flavorful and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 49,
        category: 'Wraps Veg',
        title: 'Kadai mushroom',
        price: '$12.99',
        tags: '',
        description: 'Juicy mushroom caps cooked with bell peppers, onions, tomatoes, and a blend of aromatic spices, wrapped in a soft and thin rumali roti for a flavorful and convenient handheld meal.',
        todaySpecial: false,
    },
    {
        id: 50,
        category: 'Egg',
        title: 'Egg curry',
        price: '$11.99',
        tags: '',
        description: 'Boiled eggs simmered in a flavorful curry sauce made with onions, tomatoes, and a blend of aromatic spices, offering a delicious and hearty egg dish.',
        todaySpecial: false,
    },
    {
        id: 51,
        category: 'Egg',
        title: 'Egg pepper fry',
        price: '$11.99',
        tags: '',
        description: 'Boiled eggs stir-fried with black pepper, onions, and aromatic spices, offering a flavorful and satisfying dish.',
        todaySpecial: false,
    },
    {
        id: 52,
        category: 'Egg',
        title: 'Egg chettinadu',
        price: '$11.99',
        tags: '',
        description: 'Boiled eggs cooked in a spicy and aromatic gravy infused with the bold flavors of Chettinad cuisine, featuring a blend of roasted spices, coconut, and curry leaves, offering a flavorful and satisfying egg dish.',
        todaySpecial: false,
    },
    {
        id: 53,
        category: 'Rice and Bread',
        title: 'Garlic naan',
        price: '$2.99',
        tags: '',
        description: 'Soft and fluffy Indian bread flavored with garlic and fresh cilantro, baked in a tandoor oven to perfection, offering a delicious accompaniment to any meal.',
        todaySpecial: false,
    },
    {
        id: 54,
        category: 'Rice and Bread',
        title: 'Basmati rice',
        price: '$2.49',
        tags: '',
        description: 'Long-grain aromatic rice known for its delicate fragrance and fluffy texture, perfect as a side dish or base for various Indian curries and dishes.',
        todaySpecial: false,
    },
    {
        id: 55,
        category: 'Rice and Bread',
        title: 'Naan',
        price: '$2.49',
        tags: '',
        description: 'Soft and fluffy Indian bread, traditionally baked in a tandoor oven, offering a delicious accompaniment to any meal.',
        todaySpecial: false,
    },
    {
        id: 56,
        category: 'Rice and Bread',
        title: 'Butter Naan',
        price: '$2.49',
        tags: '',
        description: 'Soft and fluffy Indian bread brushed with melted butter, traditionally baked in a tandoor oven, offering a rich and flavorful accompaniment to any meal.',
        todaySpecial: false,
    },
    {
        id: 57,
        category: 'Rice and Bread',
        title: 'Jeera rice',
        price: '$2.49',
        tags: '',
        description: 'Aromatic basmati rice cooked with cumin seeds and other spices, offering a flavorful and fragrant side dish that pairs well with a variety of Indian curries and dishes.',
        todaySpecial: false,
    },
    {
        id: 58,
        category: 'Rice and Bread',
        title: 'Chennai Parata',
        price: '$1.99',
        tags: '',
        description: 'A traditional South Indian flatbread made from whole wheat flour dough, rolled out thin and cooked on a griddle until golden brown and crispy, offering a delightful flaky texture with a hint of buttery flavor, perfect to pair with your favorite chutney or curry for a satisfying meal.',
        todaySpecial: false,
    },
    {
        id: 59,
        category: 'desserts',
        title: 'Mango Lassi',
        price: '$3.99',
        tags: '',
        description: 'A refreshing and creamy yogurt-based drink blended with ripe mangoes, sugar, and a hint of cardamom, offering a sweet and tangy flavor with a smooth texture, perfect for cooling down on a hot day or complementing spicy Indian dishes.',
        todaySpecial: false,
    },
    {
        id: 60,
        category: 'desserts',
        title: 'Lime soda (sweet and salt)',
        price: '$3.99',
        tags: '',
        description: 'A fizzy and refreshing beverage made with freshly squeezed lime juice, soda water, sugar, and a pinch of salt, offering a delightful balance of sweet, sour, and salty flavors, perfect for quenching thirst and revitalizing the palate.',
        todaySpecial: false,
    },
    {
        id: 61,
        category: 'desserts',
        title: 'Gulab jamun',
        price: '$3.99',
        tags: '',
        description: 'Soft and sweet fried dumplings made from milk solids and flour, soaked in a sugary syrup flavored with cardamom, saffron, and rose water, offering a rich and indulgent treat popular in Indian cuisine',
        todaySpecial: false,
    },
    {
        id: 62,
        category: 'desserts',
        title: 'Rose Milk',
        price: '$3.99',
        tags: '',
        description: 'A refreshing beverage made with chilled milk infused with rose syrup, offering a fragrant and floral flavor profile, often garnished with pistachios or basil seeds for added texture and visual appeal, perfect for cooling down on a hot day or as a sweet treat.',
        todaySpecial: false,
    },
    {
        id: 63,
        category: 'desserts',
        title: 'Mint lime juice',
        price: '$3.99',
        tags: '',
        description: 'A refreshing drink made with freshly squeezed lime juice, water, sugar, and mint leaves, offering a tangy and invigorating flavor with a hint of refreshing mint, perfect for quenching thirst and revitalizing the palate on a hot day.',
        todaySpecial: false,
    },

];

export default { kebab, wraps, awards, menu };
